/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package io.jaegertracing.thriftjava;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2020-08-03")
public class DependencyLink implements org.apache.thrift.TBase<DependencyLink, DependencyLink._Fields>, java.io.Serializable, Cloneable, Comparable<DependencyLink> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DependencyLink");

  private static final org.apache.thrift.protocol.TField PARENT_FIELD_DESC = new org.apache.thrift.protocol.TField("parent", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField CHILD_FIELD_DESC = new org.apache.thrift.protocol.TField("child", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField CALL_COUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("callCount", org.apache.thrift.protocol.TType.I64, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new DependencyLinkStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new DependencyLinkTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String parent; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String child; // required
  public long callCount; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PARENT((short)1, "parent"),
    CHILD((short)2, "child"),
    CALL_COUNT((short)4, "callCount");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PARENT
          return PARENT;
        case 2: // CHILD
          return CHILD;
        case 4: // CALL_COUNT
          return CALL_COUNT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __CALLCOUNT_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PARENT, new org.apache.thrift.meta_data.FieldMetaData("parent", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CHILD, new org.apache.thrift.meta_data.FieldMetaData("child", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CALL_COUNT, new org.apache.thrift.meta_data.FieldMetaData("callCount", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DependencyLink.class, metaDataMap);
  }

  public DependencyLink() {
  }

  public DependencyLink(
    java.lang.String parent,
    java.lang.String child,
    long callCount)
  {
    this();
    this.parent = parent;
    this.child = child;
    this.callCount = callCount;
    setCallCountIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DependencyLink(DependencyLink other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetParent()) {
      this.parent = other.parent;
    }
    if (other.isSetChild()) {
      this.child = other.child;
    }
    this.callCount = other.callCount;
  }

  public DependencyLink deepCopy() {
    return new DependencyLink(this);
  }

  @Override
  public void clear() {
    this.parent = null;
    this.child = null;
    setCallCountIsSet(false);
    this.callCount = 0;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getParent() {
    return this.parent;
  }

  public DependencyLink setParent(@org.apache.thrift.annotation.Nullable java.lang.String parent) {
    this.parent = parent;
    return this;
  }

  public void unsetParent() {
    this.parent = null;
  }

  /** Returns true if field parent is set (has been assigned a value) and false otherwise */
  public boolean isSetParent() {
    return this.parent != null;
  }

  public void setParentIsSet(boolean value) {
    if (!value) {
      this.parent = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getChild() {
    return this.child;
  }

  public DependencyLink setChild(@org.apache.thrift.annotation.Nullable java.lang.String child) {
    this.child = child;
    return this;
  }

  public void unsetChild() {
    this.child = null;
  }

  /** Returns true if field child is set (has been assigned a value) and false otherwise */
  public boolean isSetChild() {
    return this.child != null;
  }

  public void setChildIsSet(boolean value) {
    if (!value) {
      this.child = null;
    }
  }

  public long getCallCount() {
    return this.callCount;
  }

  public DependencyLink setCallCount(long callCount) {
    this.callCount = callCount;
    setCallCountIsSet(true);
    return this;
  }

  public void unsetCallCount() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CALLCOUNT_ISSET_ID);
  }

  /** Returns true if field callCount is set (has been assigned a value) and false otherwise */
  public boolean isSetCallCount() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CALLCOUNT_ISSET_ID);
  }

  public void setCallCountIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CALLCOUNT_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case PARENT:
      if (value == null) {
        unsetParent();
      } else {
        setParent((java.lang.String)value);
      }
      break;

    case CHILD:
      if (value == null) {
        unsetChild();
      } else {
        setChild((java.lang.String)value);
      }
      break;

    case CALL_COUNT:
      if (value == null) {
        unsetCallCount();
      } else {
        setCallCount((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PARENT:
      return getParent();

    case CHILD:
      return getChild();

    case CALL_COUNT:
      return getCallCount();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PARENT:
      return isSetParent();
    case CHILD:
      return isSetChild();
    case CALL_COUNT:
      return isSetCallCount();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof DependencyLink)
      return this.equals((DependencyLink)that);
    return false;
  }

  public boolean equals(DependencyLink that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_parent = true && this.isSetParent();
    boolean that_present_parent = true && that.isSetParent();
    if (this_present_parent || that_present_parent) {
      if (!(this_present_parent && that_present_parent))
        return false;
      if (!this.parent.equals(that.parent))
        return false;
    }

    boolean this_present_child = true && this.isSetChild();
    boolean that_present_child = true && that.isSetChild();
    if (this_present_child || that_present_child) {
      if (!(this_present_child && that_present_child))
        return false;
      if (!this.child.equals(that.child))
        return false;
    }

    boolean this_present_callCount = true;
    boolean that_present_callCount = true;
    if (this_present_callCount || that_present_callCount) {
      if (!(this_present_callCount && that_present_callCount))
        return false;
      if (this.callCount != that.callCount)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetParent()) ? 131071 : 524287);
    if (isSetParent())
      hashCode = hashCode * 8191 + parent.hashCode();

    hashCode = hashCode * 8191 + ((isSetChild()) ? 131071 : 524287);
    if (isSetChild())
      hashCode = hashCode * 8191 + child.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(callCount);

    return hashCode;
  }

  @Override
  public int compareTo(DependencyLink other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetParent()).compareTo(other.isSetParent());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetParent()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.parent, other.parent);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetChild()).compareTo(other.isSetChild());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetChild()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.child, other.child);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCallCount()).compareTo(other.isSetCallCount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCallCount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.callCount, other.callCount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("DependencyLink(");
    boolean first = true;

    sb.append("parent:");
    if (this.parent == null) {
      sb.append("null");
    } else {
      sb.append(this.parent);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("child:");
    if (this.child == null) {
      sb.append("null");
    } else {
      sb.append(this.child);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("callCount:");
    sb.append(this.callCount);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (parent == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'parent' was not present! Struct: " + toString());
    }
    if (child == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'child' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'callCount' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DependencyLinkStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public DependencyLinkStandardScheme getScheme() {
      return new DependencyLinkStandardScheme();
    }
  }

  private static class DependencyLinkStandardScheme extends org.apache.thrift.scheme.StandardScheme<DependencyLink> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DependencyLink struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PARENT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.parent = iprot.readString();
              struct.setParentIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CHILD
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.child = iprot.readString();
              struct.setChildIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // CALL_COUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.callCount = iprot.readI64();
              struct.setCallCountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetCallCount()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'callCount' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DependencyLink struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.parent != null) {
        oprot.writeFieldBegin(PARENT_FIELD_DESC);
        oprot.writeString(struct.parent);
        oprot.writeFieldEnd();
      }
      if (struct.child != null) {
        oprot.writeFieldBegin(CHILD_FIELD_DESC);
        oprot.writeString(struct.child);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(CALL_COUNT_FIELD_DESC);
      oprot.writeI64(struct.callCount);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DependencyLinkTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public DependencyLinkTupleScheme getScheme() {
      return new DependencyLinkTupleScheme();
    }
  }

  private static class DependencyLinkTupleScheme extends org.apache.thrift.scheme.TupleScheme<DependencyLink> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DependencyLink struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.parent);
      oprot.writeString(struct.child);
      oprot.writeI64(struct.callCount);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DependencyLink struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.parent = iprot.readString();
      struct.setParentIsSet(true);
      struct.child = iprot.readString();
      struct.setChildIsSet(true);
      struct.callCount = iprot.readI64();
      struct.setCallCountIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

