/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package io.jaegertracing.thrift.sampling_manager;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2020-08-03")
public enum SamplingStrategyType implements org.apache.thrift.TEnum {
  PROBABILISTIC(0),
  RATE_LIMITING(1);

  private final int value;

  private SamplingStrategyType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static SamplingStrategyType findByValue(int value) { 
    switch (value) {
      case 0:
        return PROBABILISTIC;
      case 1:
        return RATE_LIMITING;
      default:
        return null;
    }
  }
}
