/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package io.github.avpinchuk.jaeger.crossdock.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2020-08-03")
public enum Transport implements org.apache.thrift.TEnum {
  HTTP(0),
  TCHANNEL(1),
  DUMMY(2);

  private final int value;

  private Transport(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static Transport findByValue(int value) { 
    switch (value) {
      case 0:
        return HTTP;
      case 1:
        return TCHANNEL;
      case 2:
        return DUMMY;
      default:
        return null;
    }
  }
}
